using GotaSequenceLib;
using GotaSoundIO.IO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace NitroFileLoader {
    public class Sequence : SequenceFile {
        public override void Read(FileReader r) {
            FileHeader header;
            r.OpenFile<NHeader>(out header);
            uint dataSize;
            r.OpenBlock(0, out _, out _);
            uint off = r.ReadUInt32();
            dataSize = (uint)(header.FileSize - off);
            r.Jump(off, true);
            var data = r.ReadBytes((int)dataSize).ToList();
            for (int i = data.Count - 1; i >= 0; i--) {
                if (data[i] == 0) {
                    data.RemoveAt(i);
                } else {
                    break;
                }
            }
            RawData = data.ToArray();
        }
        public override void Write(FileWriter w) {
            w.InitFile<NHeader>("SSEQ", ByteOrder.LittleEndian, null, 1);
            w.InitBlock("DATA");
            w.Write((uint)0x1C);
            w.Write(RawData);
            w.Pad(4);
            w.CloseBlock();
            w.CloseFile();
        }
        public new string[] ToText() {
            List<string> l = new List<string>();
            l.Add(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;");
            l.Add(";");
            l.Add("; " + Name + ".smft");
            l.Add(";     Generated By Nitro Studio 2");
            l.Add(";");
            l.Add(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;");
            l.Add("");
            for (int i = 0; i < Commands.Count - 1; i++) {
                bool labelAdded = false;
                var labels = PublicLabels.Where(x => x.Value == i).Select(x => x.Key);
                bool label0Added = false;
                foreach (var label in labels) {
                    if (i != 0 && !labelAdded && Commands[i - 1].CommandType == SequenceCommands.Fin) {
                        l.Add(" ");
                    }
                    if (i == 0) {
                        label0Added = true;
                    }
                    l.Add(label + ":");
                    labelAdded = true;
                }
                if (OtherLabels.Contains(i)) {
                    if (i != 0 && !labelAdded && Commands[i - 1].CommandType == SequenceCommands.Fin) {
                        l.Add(" ");
                    }
                    if (i != 0) { l.Add("_command_" + i + ":"); }
                    labelAdded = true;
                }
                if (i == 0 && !label0Added) {
                    l.Add("Sequence_Start:");
                }
                l.Add("\t" + Commands[i].ToString());
            }
            return l.ToArray();
        }
        public override SequencePlatform Platform() => new Nitro();
    }
}
