<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>GotaSoundIO</RootNamespace>
    <AssemblyName>GotaSoundIO</AssemblyName>
    <Deterministic>true</Deterministic>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Asio" Version="2.2.1" />
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="NAudio.Midi" Version="2.2.1" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="NAudio.WinForms" Version="2.2.1" />
    <PackageReference Include="NAudio.WinMM" Version="2.2.1" />
    <PackageReference Include="VGAudio" Version="2.2.1" />
  </ItemGroup>
</Project>
