<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GotaSoundIO</RootNamespace>
    <AssemblyName>GotaSoundIO</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Core" Version="2.3.0" />
    <PackageReference Include="Silk.NET.OpenAL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenAL.Soft.Native" Version="1.23.1" />
    <PackageReference Include="VGAudio" Version="2.2.1" />
  </ItemGroup>
</Project>
