<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>GotaSoundBank</RootNamespace>
    <AssemblyName>GotaSoundBank</AssemblyName>
    <Deterministic>true</Deterministic>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GotaSoundIO\GotaSoundIO.csproj" />
  </ItemGroup>
</Project>