<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>NitroStudio2</RootNamespace>
    <AssemblyName>Nitro Studio 2</AssemblyName>
    <OutputType>Exe</OutputType>
    <Deterministic>true</Deterministic>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="5.4.0-alpha0042" PrivateAssets="All" />
    <PackageReference Include="EndianBinaryIO" Version="1.1.2" />
    <PackageReference Include="Fody" Version="6.5.2" PrivateAssets="All" />
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="Microsoft.VisualBasic" Version="10.0.0" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="6.0.0-preview.5.21301.5" />
    <PackageReference Include="Microsoft.WindowsAPICodePack-Core" Version="1.1.0.2" />
    <PackageReference Include="Microsoft.WindowsAPICodePack-Shell" Version="1.1.0.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Asio" Version="2.2.1" />
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="NAudio.Midi" Version="2.2.1" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="NAudio.WinForms" Version="2.2.1" />
    <PackageReference Include="NAudio.WinMM" Version="2.2.1" />
    <PackageReference Include="ObjectListView.Official" Version="2.9.2-alpha2" />
    <PackageReference Include="Sanford.Multimedia.Midi" Version="6.6.2" />
    <PackageReference Include="ScintillaNet.SearchBox" Version="1.0.3" />
    <PackageReference Include="jacobslusser.ScintillaNET" Version="3.6.3" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Resources.Extensions" Version="6.0.0" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.0-preview.5.21301.5" />
    <PackageReference Include="System.Security.Principal.Windows" Version="6.0.0-preview.5.21301.5" />
    <PackageReference Include="VGAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GotaSequenceLib\GotaSequenceLib.csproj" />
    <ProjectReference Include="..\GotaSoundBank\GotaSoundBank.csproj" />
    <ProjectReference Include="..\GotaSoundIO\GotaSoundIO.csproj" />
    <ProjectReference Include="..\NitroFileLoader\NitroFileLoader.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Hardware\DutyCycle1.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Hardware\DutyCycle2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Hardware\DutyCycle3.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Hardware\DutyCycle4.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Hardware\DutyCycle5.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Hardware\DutyCycle6.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Hardware\DutyCycle7.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Hardware\Null.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Hardware\WhiteNoise.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="icon.ico" />
    <Content Include="libgcc_s_dw2-1.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="libstdc++-6.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="midi2sseq.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="temp.mid" />
    <Content Include="sseq2midi.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>
