<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>GotaSequenceLib</RootNamespace>
    <AssemblyName>GotaSequenceLib</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <NoWarn>$(NoWarn);NU1902;NU1903;NU1904;NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Asio" Version="2.2.1" />
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="NAudio.Midi" Version="2.2.1" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="NAudio.WinForms" Version="2.2.1" />
    <PackageReference Include="NAudio.WinMM" Version="2.2.1" />
	<PackageReference Include="Core.Sanford.Multimedia.Midi" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GotaSoundIO\GotaSoundIO.csproj" />
  </ItemGroup>
</Project>
